steps:
- task: Npm@1
  inputs:
    command: 'install'
    workingDir: 'AMF/ClientApp'
- task: NuGetToolInstaller@1
  inputs:
    versionSpec: '4.3.0'
- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: '**/*.sln'
    feedsToUse: 'select'
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'

    