steps:
- task: Npm@1
  inputs:
    command: 'install'
    workingDir: 'AMF/ClientApp'
- script: dotnet restore
- task: DotNetCoreCLI@2
  displayName: 'Install dotnetsay'
  inputs:
    command: custom
    custom: tool
    arguments: 'install -g dotnetsay'

